[package]
name = "launcher-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
rspotify = { version = "0.13", features = ["client-reqwest", "env-file", "cli"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"